### ISSUE TITLE
Operation alternatives by parameters

### ISSUE THREAD

**Issue by jpy-luke** [menu-hanke/sim-workbench#47]
Branching is currently possible only by the alternatives generator. We need to make it possible by alternative parameters for an operation

Current structure of operation params is like
```
operation_params:
  operation_tag:
    param1: value1
    param2: value2
```

I propose it will become like:
```
operation_params:
  operation_tag:
    - param1: value1
      param2: value2
    - param1: value3
      param2: value4
```

This will allow us to declare parameter alternatives as a list of 1..N objects. This can be taken into account in generators.py when forming the alternatives generators. Prepare alternative operations with each different parameter object in the list as the operation_params argument.

If needed, check yaml_library_test.py for how the concept of the list of objects is handled.
