### ISSUE TITLE
Allow operations to be parametrized with the contents of configured files

### ISSUE THREAD

**Issue by jpy-luke** [menu-hanke/sim-workbench#48]
Create an additional operation configuration section for the control.yaml, something like:

```
operation_file_params:
  operation_tag:
    setting_file_1: abc.txt
    setting_file_2: kissa123.csv
    some_arbitrary_name: interesting_file.dat
```

Read the contents of these files and combine the contents as parameters into the operation_params that operations get prepared with in generators.py. The operation function is responsible for understanding the contents.
